baseURL = "/"
languageCode = "en-us"
title = "Kyverno"
description = "Kyverno is a policy engine designed for Kubernetes"
enableRobotsTXT = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy"]

ignoreFiles = [ "^OWNERS$", "README[-]+[a-z]*\\.md", "^node_modules$"]

timeout = "30s"

# Norwegian ("no") is sometimes but not currently used for testing.
# Hindi is disabled because it's currently in development.
disableLanguages = ["hi", "no"]

[frontmatter]
date = ["date", ":filename", "publishDate", "lastmod"]

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "Smart"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = ""

[outputs]
  home = ["HTML","RSS","JSON"]

# register docsytheme as hugo module
[module]
  # uncomment line below for temporary local development of module
  # needs hugo v0.109.0 or higher and go 1.18 or higher
  # workspace = "hugo.work"
  [module.hugoVersion]
    extended = true
    min = "0.145.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
