name: "Enhancement: Documentation"
description: Recommend an enhancement to the Kyverno documentation.
title: "[Enhancement] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        What would you like to see added to the documentation?
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe what enhancement you'd like to see.
      # placeholder: Tell us what you see!
      # value: "asdf"
    validations:
      required: true
  - type: input
    id: slack
    attributes:
      label: Slack discussion
      description: >-
        If this issue is the result of a discussion thread on Slack, please provide the link to the discussion for reference.
      # placeholder: ex. email@example.com
    validations:
      required: false